# before_script:

# language: java
# jdk:
# - oraclejdk8

# script: mvn clean verify -DskipTests=false -DskipITs=false -DskipSTs=false
services:
  - postgresql

before_script:
  - psql -c 'create database Trabalho;' -U postgres
  - psql -U postgres -d Trabalho -f db/"Projeto Tópicos - Script SQL BD".sql

language: java
jdk:
- oraclejdk8

script: mvn clean verify -DskipTests=false -DskipITs=false -DskipSTs=false
