CREATE TABLE usuario (
 id SERIAL NOT NULL,
 nomeCompleto VARCHAR(50) NOT NULL,
 email VARCHAR(30) NOT NULL,
 pin NUMERIC(4) NOT NULL,
 dataNascimento VARCHAR(10) NOT NULL,
 atrib1 VARCHAR(20) NOT NULL,
 atrib2 VARCHAR(20) NOT NULL,
 atrib3 VARCHAR(20) NOT NULL
);

ALTER TABLE usuario ADD CONSTRAINT PK_usuario PRIMARY KEY (id);


CREATE TABLE senha (
 id SERIAL NOT NULL,
 descricao VARCHAR(20) NOT NULL,
 senha VARCHAR(20) NOT NULL
);

ALTER TABLE senha ADD CONSTRAINT PK_senha PRIMARY KEY (id);


ALTER TABLE senha ADD CONSTRAINT FK_senha_0 FOREIGN KEY (id) REFERENCES usuario (id);


